{{- range $serviceName, $serviceConfig := .Values.databases }}
{{- range $instance := $serviceConfig.instances }}
{{- $names := include "database.names" (dict "service" $serviceName "suffix" $instance.suffix) | fromJson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $names.k8sName }}-user
  namespace: {{ $serviceConfig.namespace }}
type: Opaque
data:
  password: {{ if $instance.passwords }}{{ default $.Values.defaultPassword.user $instance.passwords.user }}{{ else }}{{ $.Values.defaultPassword.user }}{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $names.k8sName }}-app-user
  namespace: {{ $serviceConfig.namespace }}
type: Opaque
data:
  password: {{ if $instance.passwords }}{{ default $.Values.defaultPassword.app_user $instance.passwords.app_user }}{{ else }}{{ $.Values.defaultPassword.app_user }}{{ end }}
{{- end }}
{{- end }}