apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: crossplane-system
type: Opaque
stringData:
  username: your-username
  password: your-password
  host: your-postgres-host
  port: "5432"
  database: your-database
